# Generated by Django 3.2.4 on 2023-04-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vote_number', models.IntegerField()),
                ('votes_quantity', models.IntegerField()),
            ],
        ),
    ]
